[build-system]
requires = ["setuptools>=69", "wheel", "build", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "linux-dist-metadata"
# version = "0.1.0"
description = "Tools for CI/CD pipelines"
readme = "README.md"
requires-python = ">=3.9"
authors = [{ name = "Andrew Zenk", email = "andrew.zenk@particle.io" }]
license = { text = "Apache-2.0" }

# Tell setuptools we'll provide deps dynamically (from requirements.txt)
dynamic = ["dependencies", "version"]

[project.optional-dependencies]
dev = [
  "pytest>=8",           # test runner (will run your unittest tests too)
  "coverage[toml]>=7.6", # coverage
  "ruff>=0.6",           # linter
]

[project.scripts]
resolve_version = "linux_dist_metadata.resolve_version:main"
update_release_metadata = "linux_dist_metadata.update_release_metadata:main"
json_validator = "linux_dist_metadata.json_validator:main"

[tool.setuptools]
py-modules = ["linux_dist_metadata"]
package-dir = { "" = "src" }

[tool.setuptools.dynamic]
dependencies = { file = ["requirements.txt"] }

[tool.pytest.ini_options]
testpaths = ["tests"]
# Pytest will discover unittest.TestCase tests automatically
addopts = "-q"

[tool.setuptools.packages.find]
where = ["src"]
exclude = ["tests", "tests.*", "*.tests", "*.tests.*"]

[tool.coverage.run]
branch = true
source = ["src/linux_dist_metadata"]

[tool.coverage.report]
show_missing = true
skip_covered = true

[tool.setuptools_scm]
version_file = "src/linux_dist_metadata/_version.py"
